MISC_FILES = \
  anim/cuts.dir \
  anim/cuts.img \
  anim/gta3.ini \
  anim/ped.ifp \
  data/animviewer.dat \
  data/carcols.dat \
  data/CULLZONE.DAT \
  data/default.dat \
  data/default.ide \
  data/fistfite.dat \
  data/gta3.dat \
  data/gta3.zon \
  data/handling.cfg \
  data/main.scm \
  data/map.zon \
  data/maps/comnbtm/comNbtm.col \
  data/maps/comnbtm/comnbtm.ide \
  data/maps/comnbtm/comNbtm.ipl \
  data/maps/comNbtm.ipl \
  data/maps/comntop/comNtop.col \
  data/maps/comntop/comntop.ide \
  data/maps/comntop/comNtop.ipl \
  data/maps/comNtop.ipl \
  data/maps/comroad/comroad.col \
  data/maps/comroad/comroad.ide \
  data/maps/comroad/comroad.ipl \
  data/maps/comse/comSE.col \
  data/maps/comse/comse.ide \
  data/maps/comse/comSE.ipl \
  data/maps/comSE.ipl \
  data/maps/comsw/comSW.col \
  data/maps/comsw/comsw.ide \
  data/maps/comsw/comSW.ipl \
  data/maps/comSW.ipl \
  data/maps/cull.ipl \
  data/maps/generic.ide \
  data/maps/gta3.IDE \
  data/maps/indroads/indroads.col \
  data/maps/indroads/indroads.ide \
  data/maps/indroads/indroads.ipl \
  data/maps/industne/industNE.col \
  data/maps/industne/industne.ide \
  data/maps/industne/industNE.ipl \
  data/maps/industNE.ipl \
  data/maps/industnw/industNW.col \
  data/maps/industnw/industnw.ide \
  data/maps/industnw/industNW.ipl \
  data/maps/industNW.ipl \
  data/maps/industse/industSE.col \
  data/maps/industse/industse.ide \
  data/maps/industse/industSE.ipl \
  data/maps/industSE.ipl \
  data/maps/industsw/industSW.col \
  data/maps/industsw/industsw.ide \
  data/maps/industsw/industSW.ipl \
  data/maps/industSW.ipl \
  data/maps/landne/landne.col \
  data/maps/landne/landne.ide \
  data/maps/landne/landne.ipl \
  data/maps/landsw/landsw.col \
  data/maps/landsw/landsw.ide \
  data/maps/landsw/landsw.ipl \
  data/maps/making/making.col \
  data/maps/making/making.ide \
  data/maps/making/making.ipl \
  data/maps/overview.ipl \
  data/maps/props.IPL \
  data/maps/subroads/subroads.col \
  data/maps/subroads/subroads.ide \
  data/maps/subroads/subroads.ipl \
  data/maps/suburbne.ipl \
  data/maps/suburbsw.ipl \
  data/maps/temppart/temppart.col \
  data/maps/temppart/temppart.ide \
  data/maps/temppart/temppart.ipl \
  data/object.dat \
  data/particle.cfg \
  data/paths/CHASE0.DAT \
  data/paths/CHASE1.DAT \
  data/paths/CHASE10.DAT \
  data/paths/CHASE11.DAT \
  data/paths/CHASE14.DAT \
  data/paths/CHASE16.DAT \
  data/paths/CHASE18.DAT \
  data/paths/CHASE19.DAT \
  data/paths/CHASE2.DAT \
  data/paths/CHASE3.DAT \
  data/paths/CHASE4.DAT \
  data/paths/CHASE5.DAT \
  data/paths/CHASE6.DAT \
  data/paths/CHASE7.DAT \
  data/paths/flight.dat \
  data/paths/flight2.dat \
  data/paths/flight3.dat \
  data/paths/flight4.dat \
  data/paths/tracks.dat \
  data/paths/tracks2.dat \
  data/ped.dat \
  data/pedgrp.dat \
  data/pedstats.dat \
  data/surface.dat \
  data/timecyc.dat \
  data/train.dat \
  data/train2.dat \
  data/water.dat \
  data/waterpro.dat \
  data/weapon.dat \
  gta3.ini \
  models/Coll/commer.col \
  models/Coll/generic.col \
  models/Coll/indust.col \
  models/Coll/peds.col \
  models/Coll/suburb.col \
  models/Coll/vehicles.col \
  models/Coll/weapons.col \
  models/Generic/air_vlo.DFF \
  models/Generic/arrow.DFF \
  models/Generic/loplyguy.dff \
  models/Generic/peds.dff \
  models/Generic/qsphere.DFF \
  models/Generic/sphere.DFF \
  models/Generic/weapons.dff \
  models/Generic/wheels.DFF \
  models/Generic/zonecyla.DFF \
  models/Generic/zonecylb.DFF \
  models/Generic/zonesphr.DFF \
  movies/GTAtitles.mpg \
  movies/GTAtitlesGER.mpg \
  $(if $(wildcard $(GTA_DIR)/movies/LOGO.mpg), movies/LOGO.mpg, movies/Logo.mpg) \
  TEXT/american.gxt \
  TEXT/english.gxt \
  TEXT/french.gxt \
  TEXT/german.gxt \
  TEXT/italian.gxt \
  TEXT/spanish.gxt \
  \
  models/fonts.txd \
  models/frontend.txd \
  models/generic.txd \
  models/hud.txd \
  models/menu.txd \
  models/MISC.TXD \
  models/particle.txd \
  txd/LOADSC0.TXD \
  txd/LOADSC1.TXD \
  txd/LOADSC10.TXD \
  txd/LOADSC11.TXD \
  txd/LOADSC12.TXD \
  txd/LOADSC13.TXD \
  txd/LOADSC14.TXD \
  txd/LOADSC15.TXD \
  txd/LOADSC16.TXD \
  txd/LOADSC17.TXD \
  txd/LOADSC18.TXD \
  txd/LOADSC19.TXD \
  txd/LOADSC2.TXD \
  txd/LOADSC20.TXD \
  txd/LOADSC21.TXD \
  txd/LOADSC22.TXD \
  txd/LOADSC23.TXD \
  txd/LOADSC24.TXD \
  txd/LOADSC25.TXD \
  txd/LOADSC3.TXD \
  txd/LOADSC4.TXD \
  txd/LOADSC5.TXD \
  txd/LOADSC6.TXD \
  txd/LOADSC7.TXD \
  txd/LOADSC8.TXD \
  txd/LOADSC9.TXD \
  txd/mainsc1.txd  \
  txd/mainsc2.txd  \
  txd/NEWS.TXD \
  txd/SPLASH1.TXD \
  txd/SPLASH2.TXD \
  txd/SPLASH3.TXD \
  \
  audio/sfx.SDT
