IMG_TEXTURES = \
  3d8ball.txd \
  8ballfence.txd \
  8balls.txd \
  CHANGEME.txd \
  GTAElift.txd \
  Italynrth.txd \
  TRUCKTRAIL.txd \
  aircarpark.txd \
  airgrndb.txd \
  airplane.txd \
  airport.txd \
  airportbits.txd \
  airporterminal.txd \
  airporterminal2.txd \
  airporterminal3.txd \
  airporterminal4.txd \
  airportfence.txd \
  airpshadow.txd \
  airstuff2.txd \
  amco.txd \
  archedbuilding.txd \
  area5b.txd \
  asukah.txd \
  avery.txd \
  barrelexpos.txd \
  barrier.txd \
  base.txd \
  basketballcrt.txd \
  basmntcrpark.txd \
  bball.txd \
  beach.txd \
  benches.txd \
  bigbuild.txd \
  bigsign.txd \
  bilboard.txd \
  billboard.txd \
  block4grn.txd \
  boats.txd \
  bodycast.txd \
  boigalarm.txd \
  bombdoor.txd \
  bonus.txd \
  boxes.txd \
  breifcase.txd \
  brgwall.txd \
  bridge.txd \
  bridgesupport.txd \
  bridgesupports.txd \
  bridgewee.txd \
  brokenbridge.txd \
  buildingsite.txd \
  buildinsite.txd \
  buildmainten5.txd \
  buildsite.txd \
  bullion.txd \
  buoy.txd \
  busdepot.txd \
  canopy.txd \
  cardbox.txd \
  carpark.txd \
  carparkbooth.txd \
  carparkfence.txd \
  casino.txd \
  casinogarden.txd \
  cath.txd \
  cempirest.txd \
  chimney.txd \
  china2big.txd \
  chinabanner.txd \
  chinaedge.txd \
  chinatowns.txd \
  chlight.txd \
  church.txd \
  clif22.txd \
  cliffwall.txd \
  coffee.txd \
  col1h.txd \
  colcomp4.txd \
  colcomp4b.txd \
  colcomp_new.txd \
  colmansion.txd \
  comSW_LOD.txd \
  com_centrebit.txd \
  com_police.txd \
  comartgaly.txd \
  combomb.txd \
  combridgesign.txd \
  combroadwy2.txd \
  combroadwyrd.txd \
  comdocks.txd \
  comhilo1.txd \
  comhilo3b.txd \
  comhilo3e.txd \
  comhilo3h.txd \
  comhilo3shps.txd \
  comhilo_tags.txd \
  comhospital.txd \
  comjetty.txd \
  comlights.txd \
  comlod1.txd \
  comlod2.txd \
  commuseumkb.txd \
  compark.txd \
  compier.txd \
  compolice.txd \
  compound.txd \
  comsbilboard02.txd \
  comsbilboard05.txd \
  comseroadbits.txd \
  comshopinc.txd \
  comsigns.txd \
  comsky3.txd \
  comsky5z.txd \
  comstadium.txd \
  comsub_b.txd \
  comsub_c.txd \
  comtenblock6b.txd \
  comtoilet.txd \
  comtop_jetty.txd \
  comtownhall.txd \
  comtunel.txd \
  comtunnels.txd \
  comunation.txd \
  comuni2.txd \
  condo.txd \
  cranes.txd \
  crap_jetty.txd \
  crate.txd \
  csitecutscene.txd \
  cskydark.txd \
  cskytosh.txd \
  ctenblock3c.txd \
  cunt.txd \
  curlyh.txd \
  cutbank.txd \
  cutbankgrafiti.txd \
  cutbuild1.txd \
  cutbuild2.txd \
  cutbuild3.txd \
  cutrearbuild.txd \
  cutroads.txd \
  cutrubbish.txd \
  cutscenecameras.txd \
  cutscenecar3.txd \
  cutwatertanks.txd \
  dam.txd \
  dambase.txd \
  damentrance.txd \
  damfence.txd \
  damissionfence.txd \
  dirtpass.txd \
  doccrane.txd \
  docentrance.txd \
  docfactories.txd \
  dockbit.txd \
  docklight.txd \
  docks.txd \
  docksbuild.txd \
  dockvats.txd \
  dockwall.txd \
  dogfact.txd \
  dogfood.txd \
  door.txd \
  drugs.txd \
  dynbarrels.txd \
  dynbuket.txd \
  dyncones.txd \
  dynhydrent.txd \
  dynjunk.txd \
  dynnewstnd.txd \
  dynnewstnd2.txd \
  dynphn.txd \
  dynpostbx.txd \
  dynrecycle.txd \
  dynsigns.txd \
  dyntraffic.txd \
  eighth.txd \
  electricgate.txd \
  escape.txd \
  factory.txd \
  factorym.txd \
  fdr_underpass.txd \
  fences.txd \
  fire_esc.txd \
  firescape.txd \
  firstbridge.txd \
  fishfactory.txd \
  fishmarket.txd \
  fishwall.txd \
  flatiron1b.txd \
  flatironew.txd \
  frankh.txd \
  frankiesbase.txd \
  frate.txd \
  fuckedcar.txd \
  fuzzball.txd \
  garagewood.txd \
  graveyard.txd \
  greasyjoes.txd \
  groundbitties.txd \
  heli1.txd \
  heli2.txd \
  helipad.txd \
  helixbarrier.txd \
  helixroad.txd \
  highbridge.txd \
  hospital2.txd \
  hotelkb.txd \
  icons.txd \
  importexp.txd \
  indalley.txd \
  indamcooffc.txd \
  indbar.txd \
  indbeach.txd \
  indbrownbil.txd \
  indchinablocks.txd \
  indchinabuild.txd \
  indchinaredgreen.txd \
  indchinassrt.txd \
  indclub.txd \
  inddbridge.txd \
  inddiner.txd \
  inddockland.txd \
  indhibuildns.txd \
  indhospital.txd \
  inditaly.txd \
  inditaly1.txd \
  indjos_door.txd \
  indjunk.txd \
  indland124.txd \
  indpier.txd \
  indpj.txd \
  indpolice.txd \
  indpoliceball.txd \
  indradio.txd \
  indredlitblk1b.txd \
  indredlitblk2.txd \
  indredlitblk4.txd \
  indredlitgrey.txd \
  indsupasave.txd \
  indtaxi.txd \
  indtunlrail.txd \
  indtunnel.txd \
  indust1.txd \
  indust2.txd \
  introbits.txd \
  islandLODsubCOM.txd \
  islandcomind.txd \
  islandcomsub.txd \
  islandlodind.txd \
  islandsubcom.txd \
  italyeast.txd \
  italyfalg.txd \
  italymisc.txd \
  italysht.txd \
  jetty.txd \
  joeyh.txd \
  joeys.txd \
  joeysext.txd \
  jumpbox.txd \
  junk.txd \
  keeperh.txd \
  kenjih.txd \
  kmricndo.txd \
  landsectioncomn.txd \
  laundrette.txd \
  lighthouse.txd \
  lititly.txd \
  localsignsub.txd \
  loveh.txd \
  lovies.txd \
  luggage.txd \
  luigiclub.txd \
  luigih.txd \
  maindrag.txd \
  maindragn.txd \
  maindragsb1.txd \
  maindragsb2.txd \
  mallab.txd \
  mariah.txd \
  masacre.txd \
  metal.txd \
  metals.txd \
  mickyh.txd \
  miguelh.txd \
  mikesairstuff.txd \
  mine.txd \
  mistyh.txd \
  mscpbarrier.txd \
  newbuildind.txd \
  newprojectland.txd \
  newramp.txd \
  newtownhall.txd \
  nipple.txd \
  noodle.txd \
  oddgar.txd \
  opera.txd \
  operahouse.txd \
  othersubside.txd \
  owaywall.txd \
  package.txd \
  petrol.txd \
  pharmas.txd \
  pinetrees.txd \
  pipes.txd \
  pipesc.txd \
  pjects.txd \
  pjs.txd \
  planters.txd \
  playerh.txd \
  playerint.txd \
  policind.txd \
  porn.txd \
  portabarrier.txd \
  portacabin.txd \
  posh_shopshit.txd \
  postersub.txd \
  powerbox.txd \
  projbits.txd \
  pumphouse.txd \
  pylon.txd \
  radar00.txd \
  radar01.txd \
  radar02.txd \
  radar03.txd \
  radar04.txd \
  radar05.txd \
  radar06.txd \
  radar07.txd \
  radar08.txd \
  radar09.txd \
  radar10.txd \
  radar11.txd \
  radar12.txd \
  radar13.txd \
  radar14.txd \
  radar15.txd \
  radar16.txd \
  radar17.txd \
  radar18.txd \
  radar19.txd \
  radar20.txd \
  radar21.txd \
  radar22.txd \
  radar23.txd \
  radar24.txd \
  radar25.txd \
  radar26.txd \
  radar27.txd \
  radar28.txd \
  radar29.txd \
  radar30.txd \
  radar31.txd \
  radar32.txd \
  radar33.txd \
  radar34.txd \
  radar35.txd \
  radar36.txd \
  radar37.txd \
  radar38.txd \
  radar39.txd \
  radar40.txd \
  radar41.txd \
  radar42.txd \
  radar43.txd \
  radar44.txd \
  radar45.txd \
  radar46.txd \
  radar47.txd \
  radar48.txd \
  radar49.txd \
  radar50.txd \
  radar51.txd \
  radar52.txd \
  radar53.txd \
  radar54.txd \
  radar55.txd \
  radar56.txd \
  radar57.txd \
  radar58.txd \
  radar59.txd \
  radar60.txd \
  radar61.txd \
  radar62.txd \
  radar63.txd \
  railway.txd \
  railwayg.txd \
  ramp2.txd \
  rayh.txd \
  rdpuddle.txd \
  rdsign02bk.txd \
  rdsign06.txd \
  rdsign14.txd \
  rdsign15.txd \
  rdsign17.txd \
  rdsign18bk.txd \
  rdsign19bk.txd \
  roadsign.txd \
  roadtunnel.txd \
  roadtunnelent.txd \
  rock.txd \
  rocky.txd \
  rubbish.txd \
  safe.txd \
  sal_inside.txd \
  salvatory.txd \
  sawmill.txd \
  sawmillground.txd \
  schoolbus.txd \
  securityhut.txd \
  ships.txd \
  signs.txd \
  singlelight.txd \
  smalllit.txd \
  smashbarr.txd \
  station.txd \
  sub_probridge.txd \
  sub_projects.txd \
  sub_villas.txd \
  subcanister.txd \
  subcarparc.txd \
  subcrates.txd \
  subentr.txd \
  subestbuild.txd \
  subfrates.txd \
  subglass.txd \
  subhangbox.txd \
  subhangfrate.txd \
  subhospital.txd \
  subind1.txd \
  subind2.txd \
  subind26.txd \
  subind3.txd \
  subind34.txd \
  subind4.txd \
  subind5.txd \
  subind6.txd \
  subind7.txd \
  subind8.txd \
  subindgate.txd \
  submonument.txd \
  subonramp.txd \
  subparts.txd \
  subpolice.txd \
  subsign1.txd \
  subsignpost.txd \
  subtunl10.txd \
  subuild1.txd \
  subuild10.txd \
  subuild2.txd \
  subuild3.txd \
  subuild4.txd \
  subuild5.txd \
  subuild6.txd \
  subuild7.txd \
  subuild8.txd \
  suburb1.txd \
  suburb2.txd \
  subvillabits.txd \
  subway.txd \
  subway1.txd \
  subway2.txd \
  subway_comtop.txd \
  subwayind.txd \
  subwayindt.txd \
  telegraph.txd \
  tenblk4.txd \
  tenblock6a.txd \
  tenblock6aa.txd \
  tenblocknrcp.txd \
  tenement_ground.txd \
  toilet.txd \
  tonyh.txd \
  tonys.txd \
  towerdoor.txd \
  towerlights.txd \
  trackshad.txd \
  trainstair.txd \
  trainstairst.txd \
  traintracks.txd \
  trainyard.txd \
  trees.txd \
  trees2.txd \
  treeshadow.txd \
  tunlentnew.txd \
  tunnel.txd \
  tunnels.txd \
  tw@t.txd \
  tyres.txd \
  tyrestack.txd \
  unclebj.txd \
  usedcar.txd \
  vege.txd \
  vend.txd \
  vertbridge.txd \
  walkway.txd \
  wall.txd \
  warehouse.txd \
  warehouses.txd \
  warehousesc.txd \
  washin.txd \
  wastebin.txd \
  watertower.txd \
  weebridge2.txd \
  windowlit.txd \
  wood.txd \
  woodpanels.txd \
  AIRTRAIN.TXD \
  AMBULAN.TXD \
  ARMY.TXD \
  ASUKA.TXD \
  BANKD.TXD \
  BANSHEE.TXD \
  BARRACKS.TXD \
  BELLYUP.TXD \
  BFINJECT.TXD \
  BLISTA.TXD \
  BOBCAT.TXD \
  BOGDOOR.TXD \
  BOMBER.TXD \
  BORGNINE.TXD \
  BRBOMB.TXD \
  BUS.TXD \
  BUTLER.TXD \
  B_MAN1.TXD \
  B_MAN2.TXD \
  B_MAN3.TXD \
  B_WOM1.TXD \
  B_WOM2.TXD \
  B_WOM3.TXD \
  CABBIE.TXD \
  CAS_MAN.TXD \
  CAS_WOM.TXD \
  CAT.TXD \
  CHEETAH.TXD \
  CHOPPER.TXD \
  CHUNKY.TXD \
  COACH.TXD \
  COL1.TXD \
  COL2.TXD \
  COL3.TXD \
  COLROB.TXD \
  COLT1.TXD \
  COLT2.TXD \
  COLUMB.TXD \
  CONST1.TXD \
  CONST2.TXD \
  COP.TXD \
  COP2.TXD \
  CORPSE.TXD \
  CRIMINAL01.TXD \
  CRIMINAL02.TXD \
  CS_BAN.TXD \
  CS_BOMB.TXD \
  CS_LOOT.TXD \
  CS_TRUK.TXD \
  CT_MAN1.TXD \
  CT_MAN2.TXD \
  CT_WOM1.TXD \
  CT_WOM2.TXD \
  CURLY.TXD \
  D4PROPS.TXD \
  DARKEL.TXD \
  DEADDODO.TXD \
  DEALER.TXD \
  DIABLOS.TXD \
  DOCKER1.TXD \
  DOCKER2.TXD \
  DODO.TXD \
  DONKY.TXD \
  EIGHT.TXD \
  EIGHT2.TXD \
  EITDOOR.TXD \
  ENFORCER.TXD \
  ESPERANT.TXD \
  FAN_MAN1.TXD \
  FAN_MAN2.TXD \
  FAN_WOM.TXD \
  FATFEMALE01.TXD \
  FATFEMALE02.TXD \
  FATMALE01.TXD \
  FATMALE02.TXD \
  FBI.TXD \
  FBICAR.TXD \
  FEMALE01.TXD \
  FEMALE02.TXD \
  FEMALE03.TXD \
  FIREMAN.TXD \
  FIRETRUK.TXD \
  FLATBED.TXD \
  FRANKIE.TXD \
  FULCASE.TXD \
  G.TXD \
  GANG01.TXD \
  GANG02.TXD \
  GANG03.TXD \
  GANG04.TXD \
  GANG05.TXD \
  GANG06.TXD \
  GANG07.TXD \
  GANG08.TXD \
  GANG09.TXD \
  GANG10.TXD \
  GANG11.TXD \
  GANG12.TXD \
  GANG13.TXD \
  GANG14.TXD \
  GANGP.TXD \
  GHOST.TXD \
  GOON.TXD \
  HOODS.TXD \
  HOS_MAN.TXD \
  HOS_WOM.TXD \
  IDAHO.TXD \
  INFERNUS.TXD \
  ISLANDIND.TXD \
  JOEDOOR.TXD \
  JOEY.TXD \
  JOEY2.TXD \
  KEEPER.TXD \
  KENJI.TXD \
  KURUMA.TXD \
  LANDSTAL.TXD \
  LIFT.TXD \
  LINERUN.TXD \
  LIPS.TXD \
  LI_MAN1.TXD \
  LI_MAN2.TXD \
  LI_WOM1.TXD \
  LI_WOM2.TXD \
  LOVE.TXD \
  LOVE2.TXD \
  LUDOOR.TXD \
  LUIGI.TXD \
  MAFIA.TXD \
  MALE01.TXD \
  MALE02.TXD \
  MALE03.TXD \
  MANANA.TXD \
  MARIA.TXD \
  MEDIC.TXD \
  MICKY.TXD \
  MIGUEL.TXD \
  MINNOTE.TXD \
  MISTY.TXD \
  MOD_MAN.TXD \
  MOD_WOM.TXD \
  MOONBEAM.TXD \
  MRWHOOP.TXD \
  MRWONGS.TXD \
  MULE.TXD \
  NOTE.TXD \
  NOVY.TXD \
  OJG.TXD \
  OJG2.TXD \
  OJG_P.TXD \
  PANLANT.TXD \
  PATRIOT.TXD \
  PEREN.TXD \
  PIMP.TXD \
  PLASTER.TXD \
  PLAYER.TXD \
  PLAYERP.TXD \
  PLAYERX.TXD \
  POLICE.TXD \
  PONY.TXD \
  PREDATOR.TXD \
  PROSTITUTE.TXD \
  PROSTITUTE2.TXD \
  P_MAN1.TXD \
  P_MAN2.TXD \
  P_WOM1.TXD \
  P_WOM2.TXD \
  RAY.TXD \
  RCBANDIT.TXD \
  REBEL.TXD \
  REEFER.TXD \
  RHINO.TXD \
  RIFLE.TXD \
  ROBBER.TXD \
  RUMPO.TXD \
  SAM.TXD \
  SCUM_MAN.TXD \
  SCUM_WOM.TXD \
  SECURICA.TXD \
  SENTINEL.TXD \
  SHDOOR.TXD \
  SHIP.TXD \
  SHOPPER1.TXD \
  SHOPPER2.TXD \
  SHOPPER3.TXD \
  SPEEDER.TXD \
  STALLION.TXD \
  STINGER.TXD \
  STRETCH.TXD \
  STUD_MAN.TXD \
  STUD_WOM.TXD \
  STU_MAN.TXD \
  STU_WOM.TXD \
  ST_MAN.TXD \
  ST_WOM.TXD \
  SWAT.TXD \
  S_GUARD.TXD \
  TANNER.TXD \
  TAXI.TXD \
  TAXI_D.TXD \
  TONY.TXD \
  TOYZ.TXD \
  TRAIN.TXD \
  TRASH.TXD \
  TROLL.TXD \
  WHIP.TXD \
  WORKER1.TXD \
  WORKER2.TXD \
  YAKUZA.TXD \
  YANKEE.TXD \
  YARDIE.TXD
